version: '3'
volumes:
    grav_source:
        driver: local

services:
    php:
        image: ericpoe/grav-fpm:7.1
        volumes:
            - grav_source:/var/www/html
            - ./user:/var/www/html/user
        ports:
            - "9000:9000"
    web:
        image: nginx:alpine
        ports:
            - "3030:80"
        volumes:
            - grav_source:/var/www/html
            - ./user:/var/www/html/user
            - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
            - ./log/error.log:/var/log/nginx/error.log
            - ./log/access.log:/var/log/nginx/access.log
        environment:
            - NGINX_USER = www-data
        links:
            - php
